### ISSUE TITLE
"System.IO.FileNotFoundException: Could not find adb" error message.

### ISSUE THREAD

**Issue by JamestsaiTW** [Redth/AndroidSdk.Tools#4]
I get this error message when I try to use [MAUI.UITesting](https://github.com/Redth/Maui.UITesting).

I trace it and why I got this error from:
[https://github.com/Redth/AndroidSdk.Tools/blob/master/AndroidSdk/AndroidSdkManager.cs](https://github.com/Redth/AndroidSdk.Tools/blob/master/AndroidSdk/AndroidSdkManager.csl)
~~~C#
static string[] KnownLikelyPaths =>
			RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ?
new string[] {
	Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), "Android", "android-sdk"),
	Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "Android", "android-sdk"),
} :
new string []
{
	Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Library", "Developer", "android-sdk-macosx"),
	Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Library", "Developer", "Xamarin", "android-sdk-macosx"),
	Path.Combine("Developer", "Android", "android-sdk-macosx"),
};
~~~
 
(Just test it on Windows)
Because my "Android-SDK" don't install at "Environment.SpecialFolder.ProgramFiles", so I got this error.  
When I move my "Android-SDK" folder to "Environment.SpecialFolder.ProgramFiles", it works well.  

(All platform)
So, I suggest it can throw a detail exception message for user, even allow us can pass custom path for "Android-SDK" folder to the library, thanks.

**Comment by igotinfected** [comment]
Exact same issue here, trying to use `MAUI.UITesting` but I have my android SDK installed on a second drive.

**Comment by Redth** [comment]
This should be fixed in more recent versions.
